#!/usr/bin/env tsx
/**
 * BYOK env setup — local HTML form (workspace-view serve pattern).
 *
 *   tsx scripts/setup/env.ts --mode check
 *   tsx scripts/setup/env.ts --mode serve --port 3848
 */

import { createServer, type IncomingMessage } from 'node:http';
import { writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { parseArgs } from 'node:util';

import {
  envExamplePath,
  envLocalPath,
  hasYoutubeApiKey,
  loadSkillEnv,
  SKILL_ROOT,
} from '../lib/skill-root.ts';
import { renderSetupEnvHtml, renderSetupEnvSavedHtml } from '../lib/setup/env-html.ts';
import type { EnvCheckResult, EnvServeStarted } from '../lib/types/setup.ts';

const DEFAULT_PORT = 3848;

function parsePositiveInt(raw: string | undefined, fallback: number): number {
  if (raw === undefined) return fallback;
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 1 || n > 65535) {
    emit({ ok: false, code: 'validation_error', message: 'port must be 1–65535', skillRoot: SKILL_ROOT });
    process.exit(1);
  }
  return n;
}

function emit(payload: EnvCheckResult | EnvServeStarted | Record<string, unknown>): void {
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

async function readBody(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
}

function parseFormBody(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const part of body.split('&')) {
    const [k, v] = part.split('=').map((s) => decodeURIComponent(s.replace(/\+/g, ' ')));
    if (k) out[k] = v ?? '';
  }
  return out;
}

function writeEnvLocal(youtubeApiKey: string): void {
  const lines = [
    '# Generated by youpd setup/env — do not commit',
    `YOUTUBE_API_KEY=${youtubeApiKey.trim()}`,
    '',
  ];
  writeFileSync(envLocalPath(), lines.join('\n'), { mode: 0o600 });
  process.env.YOUTUBE_API_KEY = youtubeApiKey.trim();
}

function runCheck(): void {
  loadSkillEnv();
  const configured = hasYoutubeApiKey();
  const payload: EnvCheckResult = configured
    ? {
        ok: true,
        skillRoot: SKILL_ROOT,
        youtubeKeyConfigured: true,
        envLocalPath: envLocalPath(),
      }
    : {
        ok: false,
        code: 'missing_api_key',
        message:
          'YOUTUBE_API_KEY 가 없습니다. `tsx scripts/setup/env.ts --mode serve` 로 브라우저에서 입력하세요.',
        skillRoot: SKILL_ROOT,
      };
  emit(payload);
  process.exit(configured ? 0 : 1);
}

async function runServe(host: string, port: number): Promise<void> {
  const token = randomBytes(24).toString('hex');
  const html = renderSetupEnvHtml({ token, port });

  const server = createServer(async (req, res) => {
    try {
      if (req.method === 'GET' && (req.url === '/' || req.url?.startsWith('/?'))) {
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
        res.end(html);
        return;
      }

      if (req.method === 'POST' && req.url === '/save') {
        const body = await readBody(req);
        const form = parseFormBody(body);
        if (form.token !== token) {
          res.writeHead(403, { 'Content-Type': 'text/plain; charset=utf-8' });
          res.end('Invalid token');
          return;
        }
        const key = form.youtubeApiKey?.trim() ?? '';
        if (!key) {
          res.writeHead(400, { 'Content-Type': 'text/plain; charset=utf-8' });
          res.end('YOUTUBE_API_KEY required');
          return;
        }
        writeEnvLocal(key);
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
        res.end(renderSetupEnvSavedHtml());
        server.close();
        return;
      }

      res.writeHead(404);
      res.end('Not found');
    } catch (err) {
      res.writeHead(500);
      res.end((err as Error).message);
    }
  });

  await new Promise<void>((resolve, reject) => {
    server.on('error', reject);
    server.listen(port, host, () => resolve());
  });

  const result: EnvServeStarted = {
    ok: true,
    mode: 'serve',
    url: `http://${host}:${port}/`,
    host,
    port,
    skillRoot: SKILL_ROOT,
    message: '브라우저에서 YouTube API 키를 입력·저장한 뒤 이 프로세스를 종료하세요.',
  };
  emit(result);

  await new Promise<void>(() => {});
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      mode: { type: 'string', default: 'check' },
      port: { type: 'string', short: 'p' },
      host: { type: 'string' },
    },
    strict: true,
    allowPositionals: false,
  });

  const mode = values.mode ?? 'check';
  if (mode !== 'check' && mode !== 'serve') {
    emit({ ok: false, code: 'validation_error', message: '--mode must be check or serve', skillRoot: SKILL_ROOT });
    process.exit(1);
  }

  if (mode === 'check') {
    runCheck();
    return;
  }

  const host = values.host ?? '127.0.0.1';
  const port = parsePositiveInt(values.port, DEFAULT_PORT);
  await runServe(host, port);
}

main().catch((err) => {
  emit({
    ok: false,
    code: 'validation_error',
    message: (err as Error).message,
    skillRoot: SKILL_ROOT,
    examplePath: envExamplePath(),
  });
  process.exit(1);
});
